from django.utils.translation import gettext_lazy as t

ACCOUNT_TYPE_ORGANIZATIONAL = 'organizational'
ACCOUNT_TYPE_PERSONAL = 'personal'

ACCOUNT_TYPE_CHOICES = (
    (ACCOUNT_TYPE_ORGANIZATIONAL, t('Organizational account')),
    (ACCOUNT_TYPE_PERSONAL, t('Personal account')),
)

ACCOUNT_STATUS_ACTIVE = 'active'
ACCOUNT_STATUS_PENDING_PAYMENT = 'pending_payment'

FORM_MANAGER_MODULE_KEY = 'form-manager'
LIBRARY_MODULE_KEY = 'library'
MANAGEMENT_MODULE_KEY = 'management'
COLLECTION_MODULE_KEY = 'collection'
QUALITY_CONTROL_MODULE_KEY = 'quality-control'
MRANALYSIS_MODULE_KEY = 'mranalysis'

BASE_MODULE_KEYS = (
    FORM_MANAGER_MODULE_KEY,
    LIBRARY_MODULE_KEY,
)

ORGANIZATIONAL_MODULE_KEYS = (
    MANAGEMENT_MODULE_KEY,
    COLLECTION_MODULE_KEY,
    QUALITY_CONTROL_MODULE_KEY,
    MRANALYSIS_MODULE_KEY,
)

ALL_MODULE_KEYS = BASE_MODULE_KEYS + ORGANIZATIONAL_MODULE_KEYS

PERSONAL_STORAGE_LIMIT_BYTES = 500 * 1024 * 1024
