name: npm-test

on:
  push:
    branches: [ master, beta ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          cache: 'npm'
      - name: Downgrading npm to 8.5.5
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '8.5.5'
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: npm install
      - run: npm run copy-fonts
      - run: npm run build
      - run: npm run test
